const ALERT_CONSTANTS = {
	SUCCESS: 'ALERT_SUCCESS',
	ERROR: 'ALERT_ERROR',
	SECONDARY: 'ALERT_SECONDARY',
	CLEAR: 'ALERT_CLEAR',
	WARNING: 'ALERT_WARNING',
}
const META_CONSTANTS = {
	COUNTRY_META: {
		REQUEST: 'COUNTRY_META_REQUEST',
		SUCCESS: 'COUNTRY_META_SUCCESS',
		FAILURE: 'COUNTRY_META_FAILURE',
	},
	COUNTRY_LIST: {
		REQUEST: 'COUNTRY_LIST_REQUEST',
		SUCCESS: 'COUNTRY_LIST_SUCCESS',
		FAILURE: 'COUNTRY_LIST_FAILURE',
	},
}

const AUTH_CONSTANTS = {
	AUTH_SIGNUP: {
		REQUEST: 'AUTH_SIGNUP_REQUEST',
		SUCCESS: 'AUTH_SIGNUP_SUCCESS',
		FAILURE: 'AUTH_SIGNUP_FAILURE',
	},
	AUTH_SIGNIN: {
		REQUEST: 'AUTH_SIGNIN_REQUEST',
		SUCCESS: 'AUTH_SIGNIN_SUCCESS',
		FAILURE: 'AUTH_SIGNIN_FAILURE',
	},
	AUTH_PHONE_VERIFY: {
		REQUEST: 'AUTH_PHONE_VERIFY_REQUEST',
		SUCCESS: 'AUTH_PHONE_VERIFY_SUCCESS',
		FAILURE: 'AUTH_PHONE_VERIFY_FAILURE',
	},
}

const HOME_CONSTANTS = {
	HOMEPAGE_META: {
		REQUEST: 'HOMEPAGE_METADATA_REQUEST',
		SUCCESS: 'HOMEPAGE_METADATA_SUCCESS',
		FAILURE: 'HOMEPAGE_METADATA_FAILURE',
	},
	HOMEPAGE: {
		REQUEST: 'HOMEPAGE_REQUEST',
		SUCCESS: 'HOMEPAGE_SUCCESS',
		FAILURE: 'HOMEPAGE_FAILURE',
	},
	MEGA_MENU: {
		REQUEST: 'MEGA_MENU_REQUEST',
		SUCCESS: 'MEGA_MENU_SUCCESS',
		FAILURE: 'MEGA_MENU_FAILURE',
	},
	FEATURED_ITEMS: {
		REQUEST: 'RECOMMENDED_ITEMS_LIST_REQUEST',
		SUCCESS: 'RECOMMENDED_ITEMS_LIST_SUCCESS',
		FAILURE: 'RECOMMENDED_ITEMS_LIST_FAILURE',
	},
}


const PRODUCTS_CONSTANTS = {
	PRODUCT_LISTING: {
		REQUEST: 'PRODUCT_LISTING_REQUEST',
		SUCCESS: 'PRODUCT_LISTING_SUCCESS',
		FAILURE: 'PRODUCT_LISTING_FAILURE',
	},
	PRODUCT_DETAIL: {
		REQUEST: 'GET_PRODUCT_DETAIL_REQUEST',
		SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
		FAILURE: 'GET_PRODUCT_DETAIL_FAILURE',
	},
	RECENTLY_VIEWED: {
		REQUEST: 'GET_RECENTLY_VIEWED_REQUEST',
		SUCCESS: 'GET_RECENTLY_VIEWED_SUCCESS',
		FAILURE: 'GET_RECENTLY_VIEWED_FAILURE',
	},
}


const MENU_ITEM_CONSTANTS = {
	ITEM: 'ITEM_ACCESSED',
}


const ERROR_CONSTANTS = {
	MESSAGE: 'ERROR_MESSAGE',
}

export {
	ALERT_CONSTANTS,
	AUTH_CONSTANTS,
	ERROR_CONSTANTS,
	HOME_CONSTANTS,
	MENU_ITEM_CONSTANTS,
    META_CONSTANTS,
	PRODUCTS_CONSTANTS
}
